// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Coin.Shared.Models
{
    public partial class OrderPricing
    {
        [Key]
        [Column("OrderPricingID")]
        public int OrderPricingId { get; set; }
        [Column("OrderID")]
        public int OrderId { get; set; }
        public decimal? DealerNetListTotal { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? DealerTotal { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? DiscountAmount { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? DiscountDollarAmount { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? PrimaryTreatment4Price { get; set; }

        [ForeignKey(nameof(OrderId))]
        [InverseProperty(nameof(OrderHeader.OrderPricing))]
        public virtual OrderHeader Order { get; set; }
    }
}